### ISSUE TITLE
Compiling gr-foo "next" against gnuradio "next"

### ISSUE THREAD

**Issue by ATL-Flaneur** [bastibl/gr-foo#12]
I'm experimenting with GNU Radio on Ubuntu 18.04 and building from the git repos. The "next" branch with 3.8 seems like the place to start new projects.

Trying to build gr-foo gives:

```
[  4%] Building CXX object lib/CMakeFiles/gnuradio-foo.dir/channel_model_impl.cc.o
In file included from /home/ayank/Documents/SDR/gr-foo/lib/channel_model_impl.cc:18:0:
/home/ayank/Documents/SDR/gr-foo/lib/channel_model_impl.h:23:10: fatal error: gnuradio/blocks/add_cc.h: No such file or directory
 #include <gnuradio/blocks/add_cc.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
lib/CMakeFiles/gnuradio-foo.dir/build.make:86: recipe for target 'lib/CMakeFiles/gnuradio-foo.dir/channel_model_impl.cc.o' failed
make[2]: *** [lib/CMakeFiles/gnuradio-foo.dir/channel_model_impl.cc.o] Error 1
CMakeFiles/Makefile2:135: recipe for target 'lib/CMakeFiles/gnuradio-foo.dir/all' failed
make[1]: *** [lib/CMakeFiles/gnuradio-foo.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
```

Should gr-foo "next" build against gnuradio "next"? If now, how much work am I looking at to make this happen? I also want to be using gr-ieee802-11.

**Comment by ATL-Flaneur** [comment]
I'll add that I see ```gnuradio/blocks/add_blk.h``` (I'm installing into ```/opt```, so this is in ```/opt/include/gnuradio/…```) but not ```gnuradio/blocks/add_cc.h```.

Building and installing gnuradio "next" goes fine, but I'm tracing down startup issues regarding finding shared libraries.

**Comment by bastibl** [comment]
At GNU Radio, there is currently a lot of stuff in the flow. (They changed the development model and merge a multi-year backlog of features.) Last time I tried, it was not really ready for use. AFAIS, everything was merged into next and next was merged into master. So I wouldn't recommend to use either. 

You could use the last release of GNU Radio with the master branch of this module, or the next of this module with the next branch of GNU Radio from some months ago.

Your compile error comes from this commit, which was recently merged. https://github.com/gnuradio/gnuradio/commit/1043222e0de551f00683a1cc9060f194adc4fc85

I'll look into it, but I think it will take some time to update all modules. Also, I don't know how to adapt the development model of my modules to play well with the new GNU Radio development model.

**Comment by bastibl** [comment]
I just wasted six hours trying to port my modules to the GR 3.8 "tech preview", but no chance....

- GR does not install all headers (see https://github.com/gnuradio/gnuradio/pull/2038)
- GR does not export the Python version that it uses. So an OOT doesn't know if Python 2 or 3 was used. In addition, GR's code to search for Python uses variables that are not defined in OOTs, which made it always use Python 2 (see https://github.com/gnuradio/gnuradio/blob/master/cmake/Modules/GrPython.cmake#L37).
- most (core) yaml files (block definitions) are broken.
- the UHD bindings are not even installed (https://github.com/gnuradio/gnuradio/blob/master/gr-uhd/CMakeLists.txt#L62)...
- hier block generation does not work
- output buffer size is not configured for flow graphs
- QT GUI is not working

At that point I gave up...

**Comment by noc0lour** [comment]
@bastibl Thanks for the effort! I currently also do not see a way forward for porting a lot of the popular OOTs. Do you have an idea how to expose the Python version the GR in question uses?

**Comment by bastibl** [comment]
My cmake is similar to the one that gr_modtool generates. What happened here was:
- I was adapting the local GrPython cmake code, since I thought the local version would take precedence, since they are put to the [front of the search path](https://github.com/gnuradio/gnuradio/blob/267d669eb21c514c18a6ee979f5cf247d251f1ad/gr-utils/python/modtool/gr-newmod/CMakeLists.txt#L42)
- But when the OOT [configures GNU Radio](https://github.com/gnuradio/gnuradio/blob/267d669eb21c514c18a6ee979f5cf247d251f1ad/gr-utils/python/modtool/gr-newmod/CMakeLists.txt#L144) it [alters the cmake module path](https://github.com/gnuradio/gnuradio/blob/master/cmake/Modules/GnuradioConfig.cmake.in#L29), putting the installed versions at the front of the search path. So later when Python is configured the installed cmake code is used.
- By default, this code is supposed to search for python 3 (even though the OOT cannot know if GR was installed with Python 2 or 3.)
- But even the default (i.e., Python 3) doesn't work, since [it uses GR_PYTHON3_MIN_VERSION](https://github.com/gnuradio/gnuradio/blob/master/cmake/Modules/GrPython.cmake#L37) to search for Python, which is not defined in an OOT.

I don't know much about cmake, but I guess GR could create a config during build (like it is done with GnuradioConfigVersion) indicating which Python version was used. And the installed GrPython.cmake should require the corresponding version.

**Comment by ATL-Flaneur** [comment]
Thanks for this detailed commentary. Between this and hearing from another source that the 3.8 branch (next) likely won't stabilize until early 2019, it's probably best to wait a few months.

**Comment by Amalinda** [comment]
Thanks for confirming this issue. I had the same. I'll try to match versions which seems the fastest solution for now.

**Comment by clint70** [comment]
Was trying to install this package, have the same issue.. running gnu radio 3.7.10.1 and fails here: 

[  4%] Building CXX object lib/CMakeFiles/gnuradio-foo.dir/burst_tagger_impl.cc.o
[  8%] Building CXX object lib/CMakeFiles/gnuradio-foo.dir/channel_model_impl.cc.o
In file included from /Users/clint/gr-foo/lib/channel_model_impl.cc:18:
/Users/clint/gr-foo/lib/channel_model_impl.h:27:10: fatal error: 'gnuradio/filter/mmse_resampler_cc.h' file not found
#include <gnuradio/filter/mmse_resampler_cc.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [lib/CMakeFiles/gnuradio-foo.dir/channel_model_impl.cc.o] Error 1
make[1]: *** [lib/CMakeFiles/gnuradio-foo.dir/all] Error 2
make: *** [all] Error 2

I see there was a lot of effort put into this last yr did this get fixed?  OR am I missing something?

**Comment by bastibl** [comment]
GNU Radio is currently transitioning to a new release. For the time, please use the master branch of this module with the maint branch of GNU Radio.

**Comment by jkbecker** [comment]
> OOT doesn't know if Python 2 or 3 was used

Whoah that seems like a big oversight. Do you know if that's going to be addressed on the gnuradio side of things at some point?

**Comment by bastibl** [comment]
This was recently fixed in 3.8. GNU Radio now exports much more configuration parameters in its cmake config, which can be read by OOTs.

See this issue https://github.com/gnuradio/gnuradio/issues/2377

**Comment by noc0lour** [comment]
Yep :+1: I'm going to write a migration guide of some sort for OOTs to help people migrate to 3.8 and new cmake.

**Comment by bastibl** [comment]
I tried porting the module to 3.8. Now it uses a *maint-3.7* branch for GR 3.7. A *maint-3.8* branch (the new default), which hopefully works with GR 3.8, and a *master* branch, which tracks API-breaking changes towards GR 3.9. As far as I understand, that's the new development model for GR.
